In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
add=arr+5
print(add)
mul=arr*5
print(mul)
exp=arr**2
print(exp)



[ 6  7  8  9 10 11]
[ 5 10 15 20 25 30]
[ 1  4  9 16 25 36]


In [14]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print("element at index 2: ",arr[2])
print("array slicing from index 1 to 4",arr[1:5])
print("array slicing using negative index",arr[-1:-5:-1])

element at index 2:  3
array slicing from index 1 to 4 [2 3 4 5]
array slicing using negative index [6 5 4 3]


In [18]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[2,3,4],[7,6,3]])
mul=arr1*arr2
mul

array([[ 2,  6, 12],
       [28, 30, 18]])

In [20]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(np.min(arr))
print(np.argmin(arr))
print(np.max(arr))
print(np.argmax(arr))

1
0
6
5


In [27]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[2,3,4],[7,6,3]])
con=np.concatenate((arr1,arr2),axis=0)
print(con)
stk=np.vstack((arr1,arr2))
stk2=np.hstack((arr1,arr2))
print(stk)
print(stk2)

[[1 2 3]
 [4 5 6]
 [2 3 4]
 [7 6 3]]
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [7 6 3]]
[[1 2 3 2 3 4]
 [4 5 6 7 6 3]]


In [30]:
import numpy as np
arr1=np.array([1,43,652,6,8])
arr2=np.array([1,7,45,7,234])
equal=arr1==arr2
greater=arr1>arr2
less=arr1<arr2
print("equal",equal)
print("less",less)
print("greater",greater)

equal [ True False False False False]
less [False False False  True  True]
greater [False  True  True False False]
